# Generated by Django 5.0.6 on 2024-06-12 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='дата оплаты', verbose_name='дата оплаты')),
                ('object_id', models.PositiveIntegerField(verbose_name='идентификатор контента')),
                ('payment_amount', models.IntegerField(help_text='введите сумму платежа', verbose_name='сумма платежа')),
                ('payment_method', models.CharField(choices=[('card', 'карта'), ('cash', 'наличные')], help_text='выберите способ оплаты', max_length=100, verbose_name='способ оплаты')),
                ('content_type', models.ForeignKey(help_text='тип контента', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contenttypes.contenttype', verbose_name='тип контента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payments',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_content_type_object_id'),
        ),
    ]
