# Generated by Django 5.0.6 on 2024-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments_payments_unique_user_content_type_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='выберите аватар', null=True, upload_to='users/avatars/%Y/%m/%d', verbose_name='аватар'),
        ),
    ]
