# Generated by Django 5.0.6 on 2024-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='object_id',
            field=models.PositiveIntegerField(auto_created=True, verbose_name='идентификатор контента'),
        ),
    ]
