# Generated by Django 5.0.6 on 2024-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='идентификатор контента'),
        ),
    ]
