# Generated by Django 5.0.6 on 2024-06-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_object_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_url',
            field=models.URLField(blank=True, help_text='ссылка на оплату', null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(default='created', help_text='статус платежа', max_length=50, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='идентификатор цены', max_length=255, null=True, verbose_name='идентификатор цены'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='идентификатор продукта', max_length=255, null=True, verbose_name='идентификатор продукта'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='идентификатор сессии', max_length=255, null=True, verbose_name='идентификатор сессии'),
        ),
    ]
