# Generated by Django 5.0.6 on 2024-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_payments_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_url',
            field=models.URLField(blank=True, help_text='ссылка на оплату', max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='идентификатор сессии', max_length=400, null=True, verbose_name='идентификатор сессии'),
        ),
    ]
