# Generated by Django 5.0.6 on 2024-06-08 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(blank=True, help_text='выберите превью курса', null=True, upload_to='courses/preview/%Y/%m/%d', verbose_name='превью курса')),
                ('description', models.TextField(blank=True, help_text='введите описание курса', null=True, verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(blank=True, help_text='выберите превью урока', null=True, upload_to='lessons/preview/%Y/%m/%d', verbose_name='превью урока')),
                ('description', models.TextField(blank=True, help_text='введите описание урока', null=True, verbose_name='описание урока')),
                ('link_to_video', models.URLField(help_text='введите ссылку на видео', verbose_name='ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.course')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
