# Generated by Django 5.0.6 on 2024-06-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='введите название урока', max_length=100, verbose_name='название урока'),
        ),
    ]
