# Generated by Django 5.0.6 on 2024-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='введите цену курса', max_digits=8, null=True, verbose_name='цена курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='введите цену урока', max_digits=10, null=True, verbose_name='цена урока'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='цена подписки'),
        ),
    ]
